### ISSUE TITLE
[Todo] v0.1

### ISSUE THREAD

**Issue by Sirius207** [Sirius207/Optimize#1]
# Tasks

## 表格
- [ ] 呈現 一週計畫表格
- [ ] 能選擇區間 (週) 呈現 對應表格

## 表格 > 單格

- - - 
### Basic
- [ ] 能 輸入 該時段 時間使用方式
- [ ] 更新內容後 能 自動儲存 目前 時間使用方式
- [ ] 能以 顏色 區分 不同時間使用種類 (e.g. Study, Entertainment, Projects, SelfLearning, Important)
- [ ] 能 複製 與 貼上 該格內容(含顏色) 到 其他格

### Advance
- [ ] 輸入時 能以 "||" 自動拆分半小時任務
- [ ] 輸入時 能以 空格 區分 子任務 (e.g. St SE ch1 )
- [ ] 輸入時 能根據 目前輸入之內容 顯示 建立過的 子任務 文字
- [ ] 輸入後 能根據 單格內容 之 空格 自動創建子任務
- 

## 統計報告
- [ ] 能查看 該週時間使用種類分佈 
- [ ] 能查看 跨週時間使用種類曲線
- 
- [ ] 能調整 時間使用目標 (e.g. Study: 6 Pomodoro)
- [ ] 能根據 時間使用目標 計算 該週時間利用評分
- 
- [ ] 能顯示 某類子任務 所花費時間 並於 輸入任務時 顯示 預估時數
- [ ] 能顯示 該日 不同時段 時間使用種類 機率

## 計畫
- [ ] 能新增 專案 與 子計畫 與 子任務 與 預估花費時間

## 例行習慣/任務
- [ ] 能新增 例行公事，並以 方塊式 呈現 完成狀況分佈
